src/java/bean/Settings.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import java.io.Serializable;
import pojo.*;

/**
 *
 * @author efI
 */
public class Settings implements Serializable {

    private Priority defaultPrio = Priority.WICHTIG;
    private Typ defaultTyp = Typ.Auftrag_NV;
    private State defaultStatus = State.OFFEN;

    private String defaultLeistung;
    private String defaultLösungsm;
    private boolean checkbox = true;

    public Priority getDefaultPrio() {
        return defaultPrio;
    }

    public void setDefaultPrio(Priority defaultPrio) {
        this.defaultPrio = defaultPrio;
    }

    public Typ getDefaultTyp() {
        return defaultTyp;
    }

    public void setDefaultTyp(Typ defaultTyp) {
        this.defaultTyp = defaultTyp;
    }

    public State getDefaultStatus() {
        return defaultStatus;
    }

    public void setDefaultStatus(State defaultStatus) {
        this.defaultStatus = defaultStatus;
    }

    public String getDefaultLeistung() {
        return defaultLeistung;
    }

    public void setDefaultLeistung(String defaultLeistung) {
        this.defaultLeistung = defaultLeistung;
    }

    public String getDefaultLösungsm() {
        return defaultLösungsm;
    }

    public void setDefaultLösungsm(String defaultLösungsm) {
        this.defaultLösungsm = defaultLösungsm;
    }

    public String checkbox() {
        String ret = "";
        if (checkbox == true) {
            ret = "_blank";
        }
        return ret;
    }

    public boolean isCheckbox() {
        return checkbox;
    }

    public void setCheckbox(boolean checkbox) {
        this.checkbox = checkbox;
    }

}

src/java/pojo/Ticket.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.faces.context.FacesContext;
import user.User;
import user.Users;

/**
 *
 * @author efI
 */
public class Ticket implements Serializable {

    private int ticketnumber;    
    private String ticket_type;
    private State state;                    //Status
    private String subject;                  //Betreff
    private Person person_in_authority;      //Zuständiger
    private Priority priority;
    private Customer customer;
    private Date startdate;
    private Date endedate;
    private String contract;                 //Vertrag
    private String effort;                   //Leistung
    private String deadline;
    private String method_of_solution;
    private Typ supporttyp;
    private String product;
    private String address;
    private String description;
    private String channel_of_communication;
    private boolean allocation_of_project;   //Projektzuordnung
    private boolean internalprocess;         //internerVorgang
    private Person contactperson;
    private String client;                   //Mandant
    private Date lastmodified;
    private List<History> history_list = new ArrayList<>();
    private History hist = new History();
    private boolean msentbefore;    //Mailsentbefore
    private String firm_number;
    private String artikel_number;
    private String serial_number;

    public Ticket() {
    }

    public Ticket(int ticketnumber) {
        this.ticketnumber = ticketnumber;
    }

    public Ticket(int ticketnumber, String type, State state, String subject, Person person_in_authority, Priority priority, Customer customer, Date startdate, Date endedate, String contract, String effort, String deadline, String method_of_solution, Typ supporttyp, String product, String address, String description, String channel_of_communication, boolean allocation_of_project, boolean internalprocess, Person contactperson, String client, Date lastmodified, boolean msendbefore) {
        this.ticketnumber = ticketnumber;
        this.ticket_type = type;
        this.state = state;
        this.subject = subject;
        this.person_in_authority = person_in_authority;
        this.priority = priority;
        this.customer = customer;
        this.startdate = startdate;
        this.endedate = endedate;
        this.contract = contract;
        this.effort = effort;
        this.deadline = deadline;
        this.method_of_solution = method_of_solution;
        this.supporttyp = supporttyp;
        this.product = product;
        this.address = address;
        this.description = description;
        this.channel_of_communication = channel_of_communication;
        this.allocation_of_project = allocation_of_project;
        this.internalprocess = internalprocess;
        this.contactperson = contactperson;
        this.client = client;
        this.lastmodified = lastmodified;
        this.msentbefore = msendbefore;
        
        addTickettoUser();
    }

    public Ticket(int ticketnumber, String ticket_type, State state, String subject, Person person_in_authority, Priority priority, Date startdate, String description, Date lastmodified, String firm_number, String artikel_number, String serial_number) {
        this.ticketnumber = ticketnumber;
        this.ticket_type = ticket_type;
        this.state = state;
        this.subject = subject;
        this.person_in_authority = person_in_authority;
        this.priority = priority;
        this.startdate = startdate;
        this.description = description;
        this.lastmodified = lastmodified;
        this.firm_number = firm_number;
        this.artikel_number = artikel_number;
        this.serial_number = serial_number;
    }
    
    

    private void addTickettoUser() {
        FacesContext context = FacesContext.getCurrentInstance();
        Users users = (Users) context.getApplication().evaluateExpressionGet(context, "#{users}", Users.class);
        List<User> user = users.getUsers();

        for (User u : user) {
            if (u.getUsername().equals(person_in_authority)) {
                int id = u.getId();
                u.setNummer(ticketnumber);
                user.set(id, u);
                users.setUsers(user);

                System.out.println(u.getUsername() + u.getId() + u.getNummern());
            }
        }
    }

    public int getTicketnumber() {
        return ticketnumber;
    }

    public void setTicketnumber(int ticketnumber) {
        this.ticketnumber = ticketnumber;
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public Person getPerson_in_authority() {
        return person_in_authority;
    }

    public void setPerson_in_authority(Person person_in_authority) {
        this.person_in_authority = person_in_authority;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }
    
    

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEndedate() {
        return endedate;
    }

    public void setEndedate(Date endedate) {
        this.endedate = endedate;
    }

    public String getContract() {
        return contract;
    }

    public void setContract(String contract) {
        this.contract = contract;
    }

    public String getEffort() {
        return effort;
    }

    public void setEffort(String effort) {
        this.effort = effort;
    }

    public String getDeadline() {
        return deadline;
    }

    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    public String getMethod_of_solution() {
        return method_of_solution;
    }

    public void setMethod_of_solution(String method_of_solution) {
        this.method_of_solution = method_of_solution;
    }

    public Typ getSupporttyp() {
        return supporttyp;
    }

    public void setSupporttyp(Typ supporttyp) {
        this.supporttyp = supporttyp;
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getChannel_of_communication() {
        return channel_of_communication;
    }

    public void setChannel_of_communication(String channel_of_communication) {
        this.channel_of_communication = channel_of_communication;
    }

    public boolean isAllocation_of_project() {
        return allocation_of_project;
    }

    public void setAllocation_of_project(boolean allocation_of_project) {
        this.allocation_of_project = allocation_of_project;
    }

    public boolean isInternalprocess() {
        return internalprocess;
    }

    public void setInternalprocess(boolean internalprocess) {
        this.internalprocess = internalprocess;
    }

    public Person getContactperson() {
        return contactperson;
    }

    public void setContactperson(Person contactperson) {
        this.contactperson = contactperson;
    }

    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public Date getLastmodified() {
        return lastmodified;
    }

    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }

    public List<History> getHistory_list() {
        return history_list;
    }

    public void setHistory_list(List<History> history_list) {
        this.history_list = history_list;
    }

    public History getHist() {
        return hist;
    }

    public void setHist(History hist) {
        this.hist = hist;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public boolean isMsentbefore() {
        return msentbefore;
    }

    public void setMsentbefore(boolean msentbefore) {
        this.msentbefore = msentbefore;
    }    

    public String getTicketType() {
        return ticket_type;
    }

    public void setTicketType(String s) {
        this.ticket_type = s;
    }

    public String getFirm_number() {
        return firm_number;
    }

    public void setFirm_number(String firm_number) {
        this.firm_number = firm_number;
    }

    public String getArtikel_number() {
        return artikel_number;
    }

    public void setArtikel_number(String artikel_number) {
        this.artikel_number = artikel_number;
    }

    public String getSerial_number() {
        return serial_number;
    }

    public void setSerial_number(String serial_number) {
        this.serial_number = serial_number;
    }
    
    

    @Override

web/error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>Error Page not Found</div>
    </body>
</html>

web/filter_hardware_ma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="WEB-INF\template\template_ma.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:define name="content">
          
            <p:tabMenu activeIndex="0">
                <p:menuitem value="Alle Tickets" url="filter_overview_ma.xhtml" update="@all"/>
                <p:menuitem value="Meine Tickets" url="filter_myView_ma.xhtml" update="@all" />
                <p:menuitem value="Offene Tickets" url="filter_open_ma.xhtml" update="table"/>
                <p:menuitem value="Abgeschlossene Tickets" url="filter_history_ma.xhtml" update="@all" action="#{ticketBean.histTicket()}" ajax="false"/>
                <p:menuitem value="Hardware Tickets" url="filter_hardware_ma.xhtml" update="@all" style="color: white; background-color: #4b87ff;"/>
                <p:menuitem value="Software Tickets" url="filter_software_ma.xhtml" update="@all"/>
            </p:tabMenu>

    <p:dataTable id="table" var="data" value="#{ticketBean.hardTicket()}" rowStyleClass="#{ticketBean.checkColor(data)}"  scrollable="true" scrollHeight="570">
                  <p:column width="10%" filterBy="#{data.ticketnumber}" filterMatchMode="contains">
                    <f:facet name="header">
                        <p:outputLabel value="Ticketnr."/>
                    </f:facet>
                    <p:outputLabel value="#{data.ticketnumber}"/>
                </p:column>
            <p:column width="8%" filterBy="#{data.ticketType}" >
                    <f:facet name="header">
                        <p:outputLabel value="Typ"/>
                    </f:facet>
                <p:outputLabel value="#{data.ticketType}"/>
                </p:column>
                <p:column width="10%" filterBy="#{data.state.name}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Status"/>
                    </f:facet>
                    <p:outputLabel value="#{data.state.name}" />
                </p:column>
                <p:column width="25%" filterBy="#{data.subject}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Betreff"/>
                    </f:facet>
                    <p:commandLink value="#{data.subject}" action="#{ticketBean_rma.open(data)}"/>
                </p:column>
            
                <p:column width="15%" filterBy="#{data.person_in_authority}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Zuständiger"/>
                    </f:facet>
                    <p:outputLabel value="#{data.person_in_authority}"/>
                </p:column>
                <p:column width="15%" filterBy="#{data.priority.name}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Priorität"/>
                    </f:facet>
                    <p:outputLabel value="#{data.priority.name}"/>
                </p:column>
                <p:column width="15%">
                    <f:facet name="header">
                        <p:outputLabel value="Startzeit"/>
                    </f:facet>
                    <p:outputLabel value="#{data.startdate}">
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
                <p:column width="15%">
                    <f:facet name="header">
                        <p:outputLabel value="Letzte Bearbeitung"/>
                    </f:facet>
                    <p:outputLabel value="#{data.lastmodified}" >
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
            </p:dataTable>


    </ui:define>
</ui:composition>

web/filter_history_ma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="WEB-INF\template\template_ma.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:define name="content">
        
        
        <style type="text/css">
            @import "pictures/resources/css/design.css";
        </style>
            <p:tabMenu activeIndex="0">
                <p:menuitem value="Alle Tickets" url="filter_overview_ma.xhtml" update="@all"/>
                <p:menuitem value="Meine Tickets" url="filter_myView_ma.xhtml" update="@all" />
                <p:menuitem value="Offene Tickets" url="filter_open_ma.xhtml" update="table"/>
                <p:menuitem value="Abgeschlossene Tickets" url="filter_history_ma.xhtml" update="@all" style="color: white; background-color: #4b87ff;"/>
                <p:menuitem value="Hardware Tickets" url="filter_hardware_ma.xhtml" update="@all"/>
                <p:menuitem value="Software Tickets" url="filter_software_ma.xhtml" update="table" />
            </p:tabMenu>

        
        <p:dataTable id="table" var="data" value="#{ticketBean.histTicket()}" rowStyleClass="#{ticketBean.checkColor(data)}"  scrollable="true" scrollHeight="570">
                  <p:column width="10%" filterBy="#{data.ticketnumber}" filterMatchMode="contains">
                    <f:facet name="header">
                        
                        <p:outputLabel value="Ticketnr."/>
                    </f:facet>
                    <p:outputLabel value="#{data.ticketnumber}"/>
                    
                  </p:column><p:column width="8%" filterBy="#{data.ticketType}" >
                    <f:facet name="header">
                        <p:outputLabel value="Typ"/>
                    </f:facet>
                      <p:outputLabel value="#{data.ticketType}"/>
                </p:column>
                <p:column width="10%" filterBy="#{data.state.name}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Status"/>
                    </f:facet>
                    <p:outputLabel value="#{data.state.name}" />
                </p:column>
                <p:column width="25%" filterBy="#{data.subject}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Betreff"/>
                    </f:facet>
                    <p:commandLink value="#{data.subject}" action="#{ticketBean_rma.open(data)}"/>
                </p:column>
            
                <p:column width="15%" filterBy="#{data.person_in_authority}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Zuständiger"/>
                    </f:facet>
                    <p:outputLabel value="#{data.person_in_authority}"/>
                </p:column>
                <p:column width="15%" filterBy="#{data.priority.name}" filterFunction="#{ticketBean.filterByAny}">
                    <f:facet name="header">
                        <p:outputLabel value="Priorität"/>
                    </f:facet>
                    <p:outputLabel value="#{data.priority.name}"/>
                </p:column>
                <p:column width="15%">
                    <f:facet name="header">
                        <p:outputLabel value="Startzeit"/>
                    </f:facet>
                    <p:outputLabel value="#{data.startdate}">
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
                <p:column width="15%">
                    <f:facet name="header">
                        <p:outputLabel value="Letzte Bearbeitung"/>
                    </f:facet>
                    <p:outputLabel value="#{data.lastmodified}" >
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
            </p:dataTable>


    </ui:define>
</ui:composition>

web/filter_myView_kunde.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="WEB-INF\template\template_kunde.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:define name="content">
        
            <p:tabMenu activeIndex="0">
                <p:menuitem value="Meine Tickets" url="filter_myView_kunde.xhtml" update="@all" style="color: white; background-color: #4b87ff;"/>
            </p:tabMenu>

        <p:dataTable id="table" var="data" value="#{ticketBean.myTickets()}" rowStyleClass="#{ticketBean.checkColor(data)}"  scrollable="true" scrollHeight="570">
                  <p:column width="10%" filterBy="#{data.ticketnumber}" filterMatchMode="contains" sortBy="#{data.ticketnumber}">
                    <f:facet name="header">
                        <p:outputLabel value="Ticketnr."/>
                    </f:facet>
                    <p:outputLabel value="#{data.ticketnumber}"/>
                </p:column>
            <p:column width="8%" filterBy="#{data.ticketType}" sortBy="#{data.ticketType}">
                    <f:facet name="header">
                        <p:outputLabel value="Typ"/>
                    </f:facet>
                <p:outputLabel value="#{data.ticketType}"/>
                </p:column>
            <p:column width="10%" filterBy="#{data.state.name}" filterFunction="#{ticketBean.filterByAny}" sortBy="#{data.state.name}" >
                    <f:facet name="header">
                        <p:outputLabel value="Status"/>
                    </f:facet>
                    <p:outputLabel value="#{data.state.name}" />
                </p:column>
                <p:column width="25%" filterBy="#{data.subject}" filterFunction="#{ticketBean.filterByAny}" sortBy="#{data.subject}">
                    <f:facet name="header">
                        <p:outputLabel value="Betreff"/>
                    </f:facet>
                    <p:outputLabel value="#{data.subject}" />
                    <!--<p:commandLink value="#{data.subject}" action="#{ticketBean_rma.open(data)}"/>-->
                </p:column>
            
            <p:column width="15%" filterBy="#{data.person_in_authority}" filterFunction="#{ticketBean.filterByAny}" sortBy="#{data.person_in_authority}">
                    <f:facet name="header">
                        <p:outputLabel value="Zuständiger"/>
                    </f:facet>
                    <p:outputLabel value="#{data.person_in_authority}"/>
                </p:column>
                <p:column width="15%" sortBy="#{data.startdate}">
                    <f:facet name="header">
                        <p:outputLabel value="Startzeit"/>
                    </f:facet>
                    <p:outputLabel value="#{data.startdate}">
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
                <p:column width="15%" sortBy="#{data.lastmodified}">
                    <f:facet name="header">
                        <p:outputLabel value="Letzte Bearbeitung"/>
                    </f:facet>
                    <p:outputLabel value="#{data.lastmodified}" >
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
            </p:dataTable>


    </ui:define>
</ui:composition>


web/filter_myView_ma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="WEB-INF\template\template_ma.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:define name="content">
        
            <p:tabMenu activeIndex="0">
                <p:menuitem value="Alle Tickets" url="filter_overview_ma.xhtml" update="@all"/>
                <p:menuitem value="Meine Tickets" url="filter_myView_ma.xhtml" update="@all" style="color: white; background-color: #4b87ff;"/>
               <p:menuitem value="Offene Tickets" url="filter_open_ma.xhtml" update="table"/>
                <p:menuitem value="Abgeschlossene Tickets" url="filter_history_ma.xhtml" update="@all"/>
            <p:menuitem value="Hardware Tickets" url="filter_ma/filter_hardware_ma.xhtml" update="@all" />
            <p:menuitem value="Software Tickets" url="filter_software_ma.xhtml" update="@all"/>
            </p:tabMenu>

        <p:dataTable id="table" var="data" value="#{ticketBean.myTickets()}" rowStyleClass="#{ticketBean.checkColor(data)}"  scrollable="true" scrollHeight="570">
                  <p:column width="10%" filterBy="#{data.ticketnumber}" filterMatchMode="contains" sortBy="#{data.ticketnumber}">
                    <f:facet name="header">
                        <p:outputLabel value="Ticketnr."/>
                    </f:facet>
                    <p:outputLabel value="#{data.ticketnumber}"/>
                </p:column>
            <p:column width="8%" filterBy="#{data.ticketType}" sortBy="#{data.ticketType}">
                    <f:facet name="header">
                        <p:outputLabel value="Typ"/>
                    </f:facet>
                <p:outputLabel value="#{data.ticketType}"/>
                </p:column>
            <p:column width="10%" filterBy="#{data.state.name}" filterFunction="#{ticketBean.filterByAny}" sortBy="#{data.state.name}" >
                    <f:facet name="header">
                        <p:outputLabel value="Status"/>
                    </f:facet>
                    <p:outputLabel value="#{data.state.name}" />
                </p:column>
                <p:column width="25%" filterBy="#{data.subject}" filterFunction="#{ticketBean.filterByAny}" sortBy="#{data.subject}">
                    <f:facet name="header">
                        <p:outputLabel value="Betreff"/>
                    </f:facet>
                    <p:commandLink value="#{data.subject}" action="#{ticketBean_rma.open(data)}"/>
                </p:column>
            
            <p:column width="15%" filterBy="#{data.person_in_authority}" filterFunction="#{ticketBean.filterByAny}" sortBy="#{data.person_in_authority}">
                    <f:facet name="header">
                        <p:outputLabel value="Zuständiger"/>
                    </f:facet>
                    <p:outputLabel value="#{data.person_in_authority}"/>
                </p:column>
            <p:column width="15%" filterBy="#{data.priority.name}" filterFunction="#{ticketBean.filterByAny}" sortBy="#{data.priority.name}">
                    <f:facet name="header">
                        <p:outputLabel value="Priorität"/>
                    </f:facet>
                    <p:outputLabel value="#{data.priority.name}"/>
                </p:column>
                <p:column width="15%" sortBy="#{data.startdate}">
                    <f:facet name="header">
                        <p:outputLabel value="Startzeit"/>
                    </f:facet>
                    <p:outputLabel value="#{data.startdate}">
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
                <p:column width="15%" sortBy="#{data.lastmodified}">
                    <f:facet name="header">
                        <p:outputLabel value="Letzte Bearbeitung"/>
                    </f:facet>
                    <p:outputLabel value="#{data.lastmodified}" >
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" timeZone="#{ticketBean.timeZone}"/>
                    </p:outputLabel>
                </p:column>
            </p:dataTable>


    </ui:define>
</ui:composition>


web/startPage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Welcome</title>
        <style type="text/css">
            @import "pictures/resources/css/design.css";
        </style>
    </h:head>
    <h:body>

        <h:form id="from">  
            <h:panelGrid columns="3" style=" position: fixed; left: 35%; top:30%;" border="0">
                <f:facet  name="header">
                    <p:outputLabel value="Login" />
                </f:facet>
                <p:outputLabel for="name" value="Benutzername:" />
                <p:inputText id="name" value="#{loginBean.username}" required="true" requiredMessage="Bitte Daten eingeben"/>
                <p:message for="name"/>

                <p:outputLabel for="password" value="Passwort:"/>
                <p:password id="password" value="#{loginBean.password}" requiredMessage="Bitte eingeben"/>
                <p:message for="password"/>

                <p:commandButton value="Login" action="#{loginBean.doLogin()}" ajax="false"/> 
                <img src="pictures/p_advanced.png" width="130" height="37" alt="p_advanced"/>
            </h:panelGrid>

        </h:form>

    </h:body>
</html>
